### ISSUE TITLE
ImportError: cannot import name 'css'

### ISSUE THREAD

**Issue by datayeah** [akiomik/pilgram#1]
I am facing the following error when trying to run your sample. Any ideas what is wrong here?
Using it on Ubuntu with python3.

```
Traceback (most recent call last):
  File "filter.py", line 2, in <module>
    import pilgram
  File "/usr/local/lib/python3.4/dist-packages/pilgram/__init__.py", line 16, in <module>
    from pilgram._1977 import _1977
  File "/usr/local/lib/python3.4/dist-packages/pilgram/_1977.py", line 17, in <module>
    from pilgram import css
  File "/usr/local/lib/python3.4/dist-packages/pilgram/css/__init__.py", line 22, in <module>
    from pilgram.css import blending  # noqa
  File "/usr/local/lib/python3.4/dist-packages/pilgram/css/blending/__init__.py", line 21, in <module>
    from pilgram.css.blending.overlay import overlay
  File "/usr/local/lib/python3.4/dist-packages/pilgram/css/blending/overlay.py", line 15, in <module>
    from pilgram import css
ImportError: cannot import name 'css'
```

**Comment by akiomik** [comment]
Thank you for reporting!

This seems the problem that depends on a python version.
I executed the example code on ubuntu 14.04(trusty) with python 3.6, and no errors.
But I encountered the same problem as you with python 3.4. 

While I'm fixing this problem, please try higher version of python for a workaround.

**Comment by datayeah** [comment]
great! it works now! thanks for the quick fix! :)
